### ISSUE TITLE
command e4 (set number of channels) failed for 6022BL

### ISSUE THREAD

**Issue by ra1nb0w** [Ho-Ro/openhantek#5]
in macOS I see the following line
```
Sending control command e4 failed: Pipe error
```
could be an issue?

thanks

**Comment by Ho-Ro** [comment]
Hi ra1nb0w, did you use the scope with different software before? Try unplugging/replugging the scope and start again.
Reason: E4 is the control command for setting only CH1 or both CH1&CH2. This command is not available in the original Hantek firmware. OpenHantek brings a _modded_ version - but this version is not uploaded if there was already firmware uploaded to the scope's RAM.
Martin

**Comment by ra1nb0w** [comment]
Did many times. In fact when I start OpenHantek and a clean device, in my case 6022BL, it loads the new firmware
```
stop CPU
... WROTE: 792 bytes, 10 segments, avg 79
reset CPU
2nd stage: write external memory
stop CPU
2nd stage: write on-chip memory
... WROTE: 16384 bytes, 17 segments, avg 963
reset CPU
```
In the window, I see the device then it disappears then it reappears and then I can you use it.
After `compile shaders` I receive that error.

**Comment by Ho-Ro** [comment]
Ok, then it is clear - 6022BL uses a different firmware. As this device is quite rare nobody did deep investigations on the firmware. Unfortunately there are minor HW differences and 6022BL needs a different FW. 
I've implemented a different ID for BE=0x6022 and BL=0x602a. Only BE uses the command E4 -> set channel num. -> release alpha-16

@ra1nb0w  
Please check by selecting only channel CH1, deselect CH2 (also no spectrum for CH2!). 
-> only one channel visible in bottom left.

Setting __Samplerate__ should not go higher than 16 MS/s
![image](https://user-images.githubusercontent.com/12542359/54438291-b0b57980-4736-11e9-9391-af216496616a.png)

**Comment by Ho-Ro** [comment]
I take the comment https://github.com/Ho-Ro/openhantek/commit/2c464d53dc0efa23f860bbeba5c18b376f46ff3f#commitcomment-32764777 as an ok - close this issue accordingly.

**Comment by ra1nb0w** [comment]
Sorry for the delay.
- **Samplerate** goes maximum to 16 MS/s
- selecting CH1 only CH1 is shown, both bottom and in spectrum

The error still appear; in debug mode:
```
8:13:18.777: Sending control command e4: 01
Sending control command e4 failed: Pipe error
18:13:18.778: Sending control command e0: 02
18:13:18.778: Sending control command e1: 02
18:13:18.779: Sending control command e2: 1e
18:13:18.779: Sending control command e3: 01
18:13:18.779: Capture state changed to 2
18:13:18.783: Received packet 1
18:13:18.783: Starting to capture
18:13:18.887: Sending control command e4: 01
Sending control command e4 failed: Pipe error
18:13:18.890: Received packet 2
18:13:18.890: Starting to capture
18:13:18.994: Sending control command e4: 01
Sending control command e4 failed: Pipe error
```

**Comment by Ho-Ro** [comment]
I just hacked a quick fix directly into github (I'm away from my linux system). @ra1nb0w please test 
I made also good progress with the firmware - finally OpenHantek runs with the custom fw from https://github.com/Ho-Ro/Hantek6022API (this is open source c code for 8051). There are minor hw differences between 6022BE and 6022BL but it should be possible to roll a 6022BL fw version - I already know the first beta tester ;)
Martin

**Comment by ra1nb0w** [comment]
Thank you for the fast response.
Unfortunately the error is present

```
compile shaders
compile shaders
20:12:21.287: Sending control command e4: 02
Sending control command e4 failed: Pipe error
20:12:21.287: Sending control command e0: 02
20:12:21.288: Sending control command e1: 02
20:12:21.288: Sending control command e2: 10
20:12:21.288: Sending control command e3: 01
20:12:21.289: Capture state changed to 2
20:12:21.293: Received packet 1
20:12:21.293: Starting to capture
20:12:21.393: Sending control command e4: 02
Sending control command e4 failed: Pipe error
20:12:21.396: Received packet 2
20:12:21.397: Starting to capture
20:12:21.501: Sending control command e4: 02
Sending control command e4 failed: Pipe error
```
Will be a pleasure to be a beta tester.

**Comment by Ho-Ro** [comment]
@ra1nb0w Please test the new interim version 6808ea5 with custom firmware for 6022BL from https://github.com/Ho-Ro/Hantek6022API - 6022BL is untested due to missing device
As soon as it works I can drop the distinguation between BE and BL in the programm again.

**Comment by ra1nb0w** [comment]
Nice. Now no error on console but the graph freeze with always on TR (trigger) after one second of measurement. I tried to move the trigger cursor and change all parameters but it doesn't restart to draw the line. Instead the values on the bottom works correctly. If you want I can take a video. Anyway, thanks a lot!

**Comment by Ho-Ro** [comment]
_"Homework"_ for you:
1. Green light on the device stays on after freeze or does it switch to red / red blinking?
2. Trigger mode set to "Auto"?
3. Are you able to change the settings (e.g. Volt/div or Timebase) after freeze?
4. Please provide a debug output similar to the ones above from start to freeze, you can omit repeated messages in the middle. Important is the startup and the moment of freeze.
5. Did you check the python example / test programs at https://github.com/Ho-Ro/Hantek6022API? It could be easier to narrow down possible regressions between BE and BL firmware. 
6. Are you using sigrok with the scope?

Thx

**Comment by Ho-Ro** [comment]
@ra1nb0w please try latest alpha-20, new firmware is now based on sigrok
if it doesn't freeze, please check if the gain settings for both channels work correctly and independently. When I look at the fw source code it looks a little bit unclear.

**Comment by ra1nb0w** [comment]
You are so fast! I used commit d5a15c59.

> _"Homework"_ for you:
> 
> 1. Green light on the device stays on after freeze or does it switch to red / red blinking?

blink green/red

> 2. Trigger mode set to "Auto"?

With Trigger=Normal after some seconds the screen don't show nothing, either CH1 or CH2. Setting Trigger=Auto the screen come back and it works correctly (CH1, CH2). I did some tests with this configuration and seems ok. Re-enabling "Normal" the problem come back.

> 3. Are you able to change the settings (e.g. Volt/div or Timebase) after freeze?

Yes

> 4. Please provide a debug output similar to the ones above from start to freeze, you can omit repeated messages in the middle. Important is the startup and the moment of freeze.

The packet flow is correct.

```
compile shaders
compile shaders
08:11:20.342: Sending control command e4: 02
08:11:20.343: Sending control command e0: 02
08:11:20.343: Sending control command e1: 02
08:11:20.343: Sending control command e2: 0a
08:11:20.344: Sending control command e3: 01
08:11:20.345: Capture state changed to 2
08:11:20.593: Received packet 1
08:11:20.593: Starting to capture
08:11:20.943: Received packet 2
08:11:20.943: Starting to capture
08:11:21.296: Received packet 3
08:11:21.296: Starting to capture
08:11:21.649: Received packet 4
... AFTER FREEZE ...
08:12:07.238: Starting to capture
08:12:07.586: Received packet 135
08:12:07.586: Starting to capture
08:12:07.938: Received packet 136
08:12:07.939: Starting to capture
08:12:08.289: Received packet 137
08:12:08.289: Starting to capture
08:12:08.642: Received packet 138
08:12:08.643: Starting to capture
08:12:08.991: Received packet 139
08:12:08.991: Starting to capture
08:12:09.343: Received packet 140
08:12:09.343: Starting to capture
08:12:09.696: Received packet 141
08:12:09.696: Starting to capture
08:12:10.047: Received packet 142
08:12:10.047: Starting to capture
```
In my opinion the problem is related to Trigger=Normal and Scope graph flush.

> 5. Did you check the python example / test programs at https://github.com/Ho-Ro/Hantek6022API? It could be easier to narrow down possible regressions between BE and BL firmware.

No

> 6. Are you using sigrok with the scope?

No. But I can test it if you need.

> if it doesn't freeze, please check if the gain settings for both channels work correctly and independently. When I look at the fw source code it looks a little bit unclear.

What do you mean with gain?

**Comment by Ho-Ro** [comment]
The settings 5V/div, 2V/div, 1V/div, ..., 20mV/div are translated in input amplifier gain in the scope: x1, x2, x5, x10
https://github.com/Ho-Ro/Hantek6022API/blob/master/hardware/6022BE_Frontend_with%20pinout.jpg
The settings for each channel is transferred with an separate command: 
08:11:20.343: Sending control command e0: 02 - set CH1 gain 2x
08:11:20.343: Sending control command e1: 02 - set CH2 gain 2x
but are mixed in the firmware and set for both channels at one processor output port. Unfortunately BE and BL differ in the allocation of the 74HC4051 bits to the output bits of the processor - I don't have a clear documentation, also the sigrok fw looks a bit suspicious. I wonder, if setting CH1 to a defined gain alters only or also CH2 and vice-versa. 
In the meantime I dropped my try to match the different BL hardware to the recent custom firmware and took the sigrok fw (that exists for BE and BL) and adopt only the USB handling. This gives me at least the feeling that I'm based on a more mature software - but the source looks still a bit strange for BL. You are in the situation to have the exotic one of the two 6022 twins. To be honest I shortly thought also about getting this one but decided in the end to go with BE and a separate *logic analyser* like the [LCsoft board](https://sigrok.org/wiki/Lcsoft_Mini_Board), often sold as "Salaea clone" for about 10€/10$.

**Comment by ra1nb0w** [comment]
You are right but I bought the BL from a friend that he didn't use it, so this is ;-)

Test done with commit 7aef39c9717df05f968a122afb0ac358decbdeb2

> if it doesn't freeze, please check if the gain settings for both channels work correctly and independently. When I look at the fw source code it looks a little bit unclear.

To be more complete I post two screenshots; first with no load, second with 9V AC and Probe=x10

<img width="1647" alt="Screenshot 2019-03-27 at 12 36 06" src="https://user-images.githubusercontent.com/1543838/55073005-eb030d00-508c-11e9-9168-e04f28519ab3.png">
<img width="1647" alt="Screenshot 2019-03-27 at 12 35 47" src="https://user-images.githubusercontent.com/1543838/55073015-f1918480-508c-11e9-8e71-f01279e4b82f.png">

With Trigger Mode = Normal sometime the plot freeze, as before.
Ps. for the icon I already opened an issue to upstream [link](https://github.com/gamecreature/QtAwesome/issues/33)

**Comment by Ho-Ro** [comment]
Ok, your picture with the clipped AC confirms at least one of my assumptions above, that the gain setting (scope input sensitivity) of the BL firmware is incorrect. A 9 V AC gives roughly +-15 V peak values. Your /10 probe gives +- 1.5 V, the internal scope input divides also by 10 -> +- 0.15 V. The analog digital converter clips at +- 500 mV, -> the scope amplifier gain must be set to x5 to get a sine with peak +- 750 mV that is clipped at +-500. 
This narrows down to the piece of firmware that sets the gain of one channel to val = {1,2,5,10} 
At firmware cold start without any mac or linux  (or win) interaction the scope starts with gain step x5 and is (or at least should be) set accordingly by the OpenHantek program.
https://github.com/Ho-Ro/Hantek6022API/blob/master/PyHT6022/HantekFirmware/custom_BL/scope6022.c

    static BOOL set_voltage(BYTE channel, BYTE val)
    {
	BYTE bits, mask;

	switch (val) {
	case 1:
		bits = 0x02;
		break;
	case 2:
		bits = 0x01;
		break;
	case 5:
		bits = 0x00;
		break;
	case 10:
		bits = 0x03;
		break;
	default:
		return FALSE;
	}

	bits = bits << (channel ? 1 : 4);
	mask = (channel) ? 0x70 : 0x0e;
	IOA = (IOA & ~mask) | (bits & mask);

	return TRUE;
    }

At startup/reset all port bits are zero -> this selects gain step x5 for both channels.
To set the 1st channel (channel=0) the BYTE *bits* is set to either 0x02, 0x01, 0x00 or 0x03,  and shifted left 4 positions in the upper nibble (WRONG, should be << 1). But the *mask* 0x0e changes correctly the lower nibble for 1st channel. So no change occurs, same for channel=1. 
The corresponding line must look like this:
 `bits = bits << (channel ? 4 : 1);`
This code snippet was taken unchanged from sigrok firmware, I suspect that it is exactly the same gain issue there, therefore my question if you tested sigrok also.
https://github.com/sigrokproject/sigrok-firmware-fx2lafw/blob/master/hw/hantek-6022bl/fw.c

I have changed this and dropped a new 6022BL FW -> 52ef640  

Maybe this also helps with the trigger issue.

**Comment by Ho-Ro** [comment]
I got a feedback from another 6022BL user in the meantime that the new 6022BL FW 52ef640 works correctly. Also the initial error message that started this issue was already fixed. It looks like it was no special macOS topic. Therefore I rename this issue and close it.

**Comment by ra1nb0w** [comment]
with 4256693b.
Seems to work now. Thank you so much!
I notice only this strange behaviour when CH2 is not enabled
<img width="1557" alt="Screenshot 2019-04-01 at 08 55 17" src="https://user-images.githubusercontent.com/1543838/55308810-13f41b00-545c-11e9-9e5e-944bbacd6c36.png">
When CH2 is enabled it works as expected

Ps. when a stable release will be ready I push the project on macports (macOS software repository)

**Comment by Ho-Ro** [comment]
ok, got it: 
https://github.com/Ho-Ro/openhantek/blob/master/openhantek/src/hantekdso/hantekdsocontrol.cpp
line 823 should read `if ( is6022 )` instead of `if ( is6022BE )`:

    if ( is6022BE ) {
        if ( usedChannels == UsedChannels::USED_CH1 )
            modifyCommand<ControlSetNumChannels>(ControlCode::CONTROL_SETNUMCHANNELS)->setDiv( 1 );
        else
            modifyCommand<ControlSetNumChannels>(ControlCode::CONTROL_SETNUMCHANNELS)->setDiv( 2 );
    }

Your scope captures both channels but displays them *interleaved* as one trace, i.e. one point from CH1, the other from CH2 and so on ...

I changed it quickly... -> 6638cc3

**Comment by ra1nb0w** [comment]
Now seems to work fine with both channels or only one.
<img width="1557" alt="Screenshot 2019-04-01 at 12 49 39" src="https://user-images.githubusercontent.com/1543838/55322443-ab696600-547c-11e9-9b23-61cdc183d0cf.png">
Thank you!

**Comment by Ho-Ro** [comment]
One remark, I suppose that you measure AC output of a transformer and you have a noticeable DC offset of  187 and 145 mV for both channels. Do you use the calibration file ~/.config/OpenHantek/modelDSO6022.conf and did you adopt it to *your* scope? If not, maybe you should have a look at https://github.com/Ho-Ro/Hantek6022API#create-a-calibration-file-for-openhantek

**Comment by ra1nb0w** [comment]
No, I need to do calibration but I am waiting the new power supply. Thanks for explanations ;-)

**Comment by Ho-Ro** [comment]
@ra1nb0w After closing the issue #4 I decided yesterday that the program is ready to deliver - I pushed a stable v2.0 that could also go into macports.

**Comment by ra1nb0w** [comment]
FYI openhantek is now on MacPorts. thank you very much for the support! and for the development obviously ;-)

**Comment by ra1nb0w** [comment]
At the same time ;-)

**Comment by Ho-Ro** [comment]
Thx, please provide a link that I can put in the readme.

**Comment by ra1nb0w** [comment]
There is no one link but I can provide the instruction to install openhantek from a raw macOS install.

To install MaPorts use the following [link](https://guide.macports.org/#installing).
After that you can use the command
```
sudo port install openhantek
```
and then
```
OpenHantek
```
to run the program.

When I will have some free time I would change your `cmake/CPackInfos.cmake` and include Bundle OSX to produce `.app` and `.dmg`

**Comment by Ho-Ro** [comment]
Thx, it would be cool to have a correct osx package.
